apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-microservice
  labels:
    app: flask-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-microservice
  template:
    metadata:
      labels:
        app: flask-microservice
    spec:
      containers:
        - name: flask-microservice
          image: us-central1-docker.pkg.dev/github-actions-111/my-python-micro-repo/flask-microservice:latest
          # This will be overridden by the workflow with SHA-tagged image
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      imagePullSecrets:
        - name: artifact-registry
