apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-microservice
  template:
    metadata:
      labels:
        app: flask-microservice
    spec:
      containers:
      - name: flask-microservice   # Must match workflow's CONTAINER_NAME
        image: us-central1-docker.pkg.dev/github-actions-111/my-python-micro-repo/flask-microservice:latest
        ports:
        - containerPort: 8080
