name: CI/CD - Build Flask App → Artifact Registry → Deploy on GKE

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: flask-microservice
  GKE_ZONE: us-central1-a
  AR_REGION: us-central1
  REPO: my-python-micro-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/1070327104780/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: gh-actions-gke-sa@github-actions-111.iam.gserviceaccount.com

      - name: Install GKE gcloud auth plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
            sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
            sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.AR_REGION }}-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          IMAGE="${{ env.AR_REGION }}-docker.pkg.dev/github-actions-111/${{ env.REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials my-gke-cluster \
            --zone ${{ env.GKE_ZONE }} \
            --project github-actions-111

      - name: Deploy to GKE
        run: |
          IMAGE="${{ env.AR_REGION }}-docker.pkg.dev/github-actions-111/${{ env.REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          kubectl set image deployment/${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}="$IMAGE"
          kubectl rollout status deployment/${{ env.IMAGE_NAME }}
